force-app/main/default/objects/HistoricoVacinacao__c/HistoricoVacinacao__c.object-meta.xml
<CustomObject>
    <label>Histórico de Vacinação</label>
    <nameField>
        <displayFormat>HistVac - {0000}</displayFormat>
        <label>Historico de Vacinação Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos de Vacinações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HistoricoVacinacao__c/fields/DataVacinacao__c.field-meta.xml
<CustomField>
    <fullName>DataVacinacao__c</fullName>
    <label>Data da Vacinação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HistoricoVacinacao__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pet</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Históricos de Vacinações</relationshipLabel>
    <relationshipName>HistoricoVacinacao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/DataProximaVacinacao__c.field-meta.xml
<CustomField>
    <fullName>DataProximaVacinacao__c</fullName>
    <label>Data da Proxima Vacinação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/DataUltimaVacinacao__c.field-meta.xml
<CustomField>
    <fullName>DataUltimaVacinacao__c</fullName>
    <label>Data da Ultima Vacinação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Especie__c.field-meta.xml
<CustomField>
    <fullName>Especie__c</fullName>
    <label>Espécie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cachorro</fullName>
            </value>
            <value>
                <fullName>Gato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PetDAO.cls
/**
 * @Descrição               : 
 * @Autor                   : 
 * @Empresa:                : Everymind LTDA.
 * @Ultima modificação em   : 08-05-2022
 * @Ultima modificação por  : C. Vinícius Santos (c.viniciussantos@outlook.com)
**/

public  class PetDAO {
    
    public static Pet__c getPet(Id idPet){
        return [
                SELECT
                    Id, 
                    Especie__c, 
                    DataUltimaVacinacao__c, 
                    DataProximaVacinacao__c
                FROM 
                    Pet__c
                WHERE
                    Id = :idPet
        ];
    }

    public static HistoricoVacinacao__c getDataVac(Id idPet){
        return [
                SELECT
                    Id, 
                    Name, 
                    Local__c, 
                    DataVacinacao__c,
                    Pet__c
                FROM 
                    HistoricoVacinacao__c
                WHERE
                    Pet__c = :idPet
        ];
    }
}