force-app/main/default/objects/Adocao__c/Adocao__c.object-meta.xml
<CustomObject>
    <label>Adoção</label>
    <nameField>
        <displayFormat>Adoção {0000}</displayFormat>
        <label>Adoção Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoções</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adocao__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dono</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Adoções</relationshipLabel>
    <relationshipName>Adocao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Adocao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aberto</fullName>
                <default>true</default>
                <label>Aberto</label>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Aguardando busca do pet</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Reprovada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdocaoBO.cls
public  class AdocaoBO {

    public static void envioEmailAguardandoBuscaPet(List<Adocao__c> adList){

        /*Contact contato;

        for(Adocao__c adocao : adList){
            
            if(adocao.Status__c == 'Aguardando busca do pet')
                if(adocao.Contact__c != null)
                    contato = ContactDAO.getContactById(adocao.Contact__c);
            
            if(contato.Email != null)
                EmailService.enviarEmailBuscarPet(contato);
        }*/
    }
}