force-app/main/default/objects/Adocao__c/Adocao__c.object-meta.xml
<CustomObject>
    <label>Adoção</label>
    <nameField>
        <displayFormat>Adoção {0000}</displayFormat>
        <label>Adoção Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoções</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adocao__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dono</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Adoções</relationshipLabel>
    <relationshipName>Adocao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Adocao__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pet</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Adoções</relationshipLabel>
    <relationshipName>Adocoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HistoricoVacinacao__c/HistoricoVacinacao__c.object-meta.xml
<CustomObject>
    <label>Histórico de Vacinação</label>
    <nameField>
        <displayFormat>HistVac - {0000}</displayFormat>
        <label>Historico de Vacinação Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos de Vacinações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HistoricoVacinacao__c/fields/DataVacinacao__c.field-meta.xml
<CustomField>
    <fullName>DataVacinacao__c</fullName>
    <label>Data da Vacinação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HistoricoVacinacao__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pet</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Históricos de Vacinações</relationshipLabel>
    <relationshipName>HistoricoVacinacao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/DataProximaVacinacao__c.field-meta.xml
<CustomField>
    <fullName>DataProximaVacinacao__c</fullName>
    <label>Data da Proxima Vacinação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchAvisoVacina.cls
public class BatchAvisoVacina implements Database.Batchable<SObject>{
    
    public Integer registrosProcessados = 0;

    public static Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([SELECT Id, Name, Pet__c, Contact__c FROM Adocao__c]);
    }

    public void execute(Database.BatchableContext bc, List<Adocao__c> adocao){
        
        Contact dono = new Contact();
        Pet__c pet = new Pet__c();
        HistoricoVacinacao__c histVac = new HistoricoVacinacao__c();

        for(Adocao__c ad : adocao){
            dono = ContactDAO.getContactById(ad.Contact__c);
            pet = PetDAO.getPet(ad.Pet__c);
            histVac = PetDAO.getDataVac(ad.Pet__c);

            if(pet.DataProximaVacinacao__c != null && pet.DataProximaVacinacao__c < System.today())
                if(histVac.DataVacinacao__c == null || histVac.DataVacinacao__c < pet.DataProximaVacinacao__c){
                    Task tarefa = new Task();

                    if(dono != null){
                        tarefa.Contact__c = dono.Id;
                        tarefa.Status = 'In Progress';
                        tarefa.Subject = 'Deve Vacinar o Pet!';
                        tarefa.Priority = 'High';

                        insert tarefa;

                        registrosProcessados++;
                    }
                }
        }
    }

    public void finish(Database.BatchableContext bc){
        System.debug('Registros processados: '+ registrosProcessados);
    }
}